# Config for pydrive (see also their documentation and the README for this repository)
client_config_backend: settings # Don't change

client_config:
  client_id:      # Todo (2 lines): From your client_secret.json, 
  client_secret:  # which you will download from google API system. See README

save_credentials: True                        # Don't change these (unless you don't want to save credentials
save_credentials_backend: file                # which I have not tested)
save_credentials_file: saved_credentials.json # Don't chnage: This file will be created when you run. 
                                              # It saves state so you can continkue to query.

get_refresh_token: True   # Don't change

###############################
# Config for googledrivecheck #
# #############################

# Personal settings:
my_user_name:  "John Smith"     # Todo: This is the google user name for the user who is running the program
                                # This is how the program identifies files not owned by the running user
rootdirs: ["My Drive", "My Computer"]       # Todo: "My Computer" is an example -- this occurs if you backup
                                            # your local documents or other folders on your computer outside
                                            # your drive.
# For testing
tester_id: "enter_folder_or_file_id_as string"   # A file ID from which to recursively parse.
                                                 # to use Also set the "run_short_test" flag
                                                 # Not necessary unless you're
                                                 # debugging / want to check a
                                                 # certain file

# Some sensible defaults. No need to change these
orphan_prefix: "0_orphan"                   # Prefix for outputted fullpaths for orphan files
name_for_non_seeable_folders: "no_name"     # Name for any folders where metadata lookup fails

max_results_api_setting: 1000               # Default value for max results per API request (program executes
                                            # requests until all files are returned
max_metadata_fetch_try_count: 5             # How many times to try lookup before giving up.
                                            # Generally fetch never fails

# Specific query settings (i.e. what files to track). Also no need to change.
log_file_if_size_greater_than_limit: 1e8 # (100 MB)

